### ISSUE TITLE
Exercise 1- Compare users

### ISSUE THREAD

**Issue by Shruti2791** [Abdul-Azeez/javascriprepo#1]
1) Create issue for every javascript exercise you submit.
2) Please follow js style guide. (Refer this https://github.com/airbnb/javascript)
3) Class names should be Pascal cased.
4) What is the purpose of calling 'compare' method with user object if you are not using its functionality.

**Comment by Abdul-Azeez** [comment]
Done. Please check.

**Comment by Shruti2791** [comment]
No changes for point 4.

**Comment by Abdul-Azeez** [comment]
Done Please Check

**Comment by Shruti2791** [comment]
1) Exercise is not working.
2) 'user1.compare(user2)' is giving wrong results.

**Comment by Abdul-Azeez** [comment]
Please Check Again.

**Comment by Shruti2791** [comment]
1) Please follow the style guide for if-else syntax and for spaces on either side of operators.
2) Check for invalid entries also.

**Comment by Abdul-Azeez** [comment]
Done Please Check

**Comment by Abdul-Azeez** [comment]
Done. Please Check.

**Comment by Shruti2791** [comment]
Lokks fine. Good work :+1:
