### ISSUE TITLE
Exercise 10, Domain name https://github.com/Abdul-Azeez/javascriprepo/tree/master/Domain

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/javascriprepo#10]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/Domain

Create a simple form with a textfield and a submit button. When I enter a URL in this textfield and submit the form, it should alert me the domain name from the entered url. For example, If I enter:1. http://example.com/folder/file.html, then on submitting the form it should alert something like: Domain: example.co m. 2. (with subdomain) http://vinsol.example.com/folder/file.html, then on submitting the form it should alert something like:Domain: example.com, Subdomain: vinsol.Basic Idea is to extract domain name and subdomain from a URL.Note: Use Regular Expressions for this exercise.Please use only Object oriented approach to write your code.

**Comment by mkangia** [comment]
Abdul. The code seems good. Just that  its taking 'www' also as a part of the subdomain which it should not. That can be improved.

**Comment by Abdul-Azeez** [comment]
Done
