### ISSUE TITLE
javascript exercise 2 https://github.com/Abdul-Azeez/Javascript/tree/master/javascritptexercise2.

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/javascriprepo#2]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/javascritptexercise2

```
Exercise (Check all or none)Create a list of checkbox (red, green, yellow, white, black).
```

 Now create two links "Check all" and 'none'.
When you click on check all link all checkbox will be selected, and when you click on none link all checkbox will be deselected(working example is gmail).

**Comment by Abdul-Azeez** [comment]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/javascritptexercise2.

    Exercise (Check all or none)Create a list of checkb ox (red, green, yellow, white, black). Now create two links "Check all" and 'none'. When you click on check all link all checkbox will be selected, and when you click on none link all checkbox will be deselected(working example is gmail).

**Comment by abhishekjain16** [comment]
Are you sure this exercise is working?

Please fix Indentation.

**Comment by Abdul-Azeez** [comment]
Please Check.

**Comment by abhishekjain16** [comment]
Please check: 

```
 if (!countCheckBoxes) {
    objCheckBoxes.checked = CheckValue;
  }
  else
    // set the check value for all check boxes
    for(var i = 0; i < countCheckBoxes; i++) {

      objCheckBoxes[i].checked = CheckValue;
    }
  }
```

condition again.

Plus also not sure where setAllCheckBoxes is being called

**Comment by Abdul-Azeez** [comment]
Done. The SetAllCheckBoxes was called in the html. I have changed that.

**Comment by Abdul-Azeez** [comment]
Done

**Comment by abhishekjain16** [comment]
1. Do not use filename as checkbox1, it should have appropriate name.
2. countCheckBoxes, Colour, objCheckBoxes variable names are not appropriate. Please use better names for these
3. Not sure why we have following code:

```
if (!objCheckBoxes) {
    objCheckBoxes.checked = CheckValue;
  }
```
1. We can improve on setAllCheckBoxes, trying breaking it into smaller methods

**Comment by Abdul-Azeez** [comment]
Done.

**Comment by abhishekjain16** [comment]
1. Adding event listener should be function of object only.
2. Please have better names for variables, not like button and button1

**Comment by Abdul-Azeez** [comment]
Done. Please check.

**Comment by abhishekjain16** [comment]
Change as discussed

**Comment by abhishekjain16** [comment]
1. setOfToggleChecks should not be used inside ToggleCheck definition. It is an object outside its scope.

**Comment by Abdul-Azeez** [comment]
Done.
