### ISSUE TITLE
javascript exercise3 https://github.com/Abdul-Azeez/javascriprepo/tree/master/javascriptexercise3

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/javascriprepo#3]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/javascriptexercise3

Create a list of checkboxs(Sunday, Monday, Wednesday, Thursday, Tuesday, Friday, Saturday and none). Now when I start checking these checkboxs, it should not let me check more than 3 checkboxes. When I try to check on 4th checkbox it should alert me as "Only 3 days can be selected. You have already selected sunday, monday and tuesday".Now when I click on none, all other checkboxs should be deselected. Also when 'none' is selected and I select any other option(lets assume sunday), that option(sunday) will be selected and none will be deselected.

**Comment by yuktikhurana** [comment]
Please read the question carefully
1. “none” should be a checkbox  not button
2. message to show for maximum 3 selection is incorrect. It should list the name of the days you’ve already selected
3. Code can be optimised.

**Comment by Abdul-Azeez** [comment]
Done. Check

**Comment by yuktikhurana** [comment]
1. please correct the message. should be you 'cannot'
2. Please work on variable naming
3. can we move the maximum checked value to a class property ?
4. Also we can maintain a class array of currently selected days.

**Comment by Abdul-Azeez** [comment]
Done

**Comment by yuktikhurana** [comment]
I’ve 5 checkboxes group on a page. I want each one to have a different maximum count of selected checkboxes. How can we achieve this?

**Comment by Abdul-Azeez** [comment]
Done.

**Comment by yuktikhurana** [comment]
Looks Good :+1:
