### ISSUE TITLE
exercise 4: https://github.com/Abdul-Azeez/javascriprepo

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/javascriprepo#4]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/exercise4

Write a Script that prompts you for a URL. If the input is an empty url it should alert you. Otherwise it should open that URL in a new window of width 400px and height 450px, without any type of bar(status bar, scroll bars etc..).

**Comment by abhishekjain16** [comment]
1. Urluser.prototype.validate Please check this method again. This implies that "0" is invalid but "123" is valid.
2. Fix indentation for html and js code both.
3. this.validate(this.person)== true is this correct way to check?
4. `while (true) {
   alert("Please you inputed an empty string")
   return;
   }`
   not sure why we are having while loop.

**Comment by Abdul-Azeez** [comment]
Done.
