### ISSUE TITLE
exercise6 https://github.com/Abdul-Azeez/javascriprepo/tree/master/exercise6

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/javascriprepo#6]
https://github.com/Abdul-Azeez/javascriprepo/tree/master/exercise6

Exercise (Move countries from one box to the other)Create two multiple selection boxFirst box contains list of countries and when you select a country and click on add button. Selected country will disappear from first box and appear in second button. And when you select a country from second box and click on remove button it will disappear from second box and appear in first box

**Comment by mkangia** [comment]
Hey Abdul,
1) Just a practice we follow in code is to have two spaces indentation.
2) Lets not bind onclick in html unless needed. So lets keep all JS event handling in the js code and files itself.
3) the list collapses when empty. We need to avoid it.
4) Not sure if creating a new row every time is the best option on moving. Can there be a better way?

Please consider these points and resubmit

**Comment by Abdul-Azeez** [comment]
Done. Please Check

**Comment by mkangia** [comment]
Seems good..

:+1:
